version: '3.1'

services:

# PHP/Apache with mysql-client
  app:
    container_name: ${APP_PREFIX}_app
    image: codepulse/php-7.2.0-apache-mysql
    volumes:
      - .:/var/www
      - ./Docker/etc/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./Docker/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /var/www/docroot
    env_file: .env
    depends_on:
      - db
    ports:
      - "${APP_PORT}:80"
    links:
      - db:${APP_URL}
      - obtainit_solr:solr.obtainit.localhost

# Database service
  db:
    image: percona:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/etc/mysql/my.cnf:/etc/mysql/my.cnf:cached
    ports:
      - "${DB_PORT}:3336"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  obtainit_solr:
    container_name: obtainit_solr
    image: solr:6-alpine
    volumes:
      - obtainit-solr:/opt/solr/server/solr/obtainit_index_conf:cached
      - ./docroot/modules/contrib/search_api_solr/solr-conf/6.x:/solr-conf/conf:cached
    ports:
      - 8982:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - obtainit_index_conf
      - /solr-conf


# Volumes to make sure I do not lose any data
volumes:
  db_data:
  obtainit-solr:
